### ISSUE TITLE
Client ignores -datadir and -choosedatadir

### ISSUE THREAD

**Issue by lazynooblet** [continuumcoin/CTM#2]
-datadir=[path] is ignored
-choosedatadir pops up the window to choose the data directory, and then ignores the selection.

Uses default in all cases (%appdata%\Continuumcoin on Windows)

**Comment by bitsta** [comment]
thank you for the hint. i will fix this with the next update.do you have a globaly used username to add you as contributor or dev-support?kindly,bitsta

-------- Original Message --------
Subject: [CTM] Client ignores -datadir and -choosedatadir (#2)
