### ISSUE TITLE
Updated version won't compile

### ISSUE THREAD

**Issue by sirmax1** [continuumcoin/CTM#3]
Been trying to compile the latest version of CTM on 2 different linux boxes and it will not compile. The last version i compiled worked fine.

Also i noticed when i tried to update CTM src, "Git pull" it threw a bunch of errors so I wiped out the CTM folder and grabbed a fresh git of the source and still it will not compile.

**Comment by bitsta** [comment]
what error are you getting? 

-------- Original Message --------
Subject: [CTM] Updated version won't compile (#3)

**Comment by sirmax1** [comment]
Well i tried it again today and it compiled fine, i don't know if the reboot helped or what but it seems to be working now :)
